services:
  dev:
    build:
      context: .
      dockerfile: ./Dockerfile-local
    working_dir: /app
    volumes:
      - Fennel-Protocol:/app
    ports:
      - "9944:9944"
    entrypoint: cargo run --release -- --dev --tmp
volumes:
  Fennel-Protocol:
