
//! Autogenerated weights for `pallet_keystore`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-21, STEPS: `100`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("fennel-local"), DB CACHE: 1024

// Executed Command:
// ./target/release/fennel-node
// benchmark
// pallet
// --chain=fennel-local
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_keystore
// --extrinsic=*
// --steps=100
// --repeat=10
// --template=./scripts/templates/parachain-weight-template.hbs
// --output=./runtime/fennel/src/weights

#![allow(unused_parens, unused_imports)]
#![allow(clippy::unnecessary_cast, clippy::missing_docs_in_private_items)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_keystore.
pub trait WeightInfo {
	fn announce_key(s: u32, ) -> Weight;
	fn revoke_key(s: u32, ) -> Weight;
	fn issue_encryption_key(s: u32, ) -> Weight;
}

/// Weights for pallet_keystore using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Keystore IssuedKeys (r:0 w:1)
	/// Proof Skipped: Keystore IssuedKeys (max_values: None, max_size: None, mode: Measured)
	/// The range of component `s` is `[0, 100000]`.
	fn announce_key(_s: u32, ) -> Weight {
		Weight::from_parts(10_448_118, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Keystore IssuedKeys (r:0 w:1)
	/// Proof Skipped: Keystore IssuedKeys (max_values: None, max_size: None, mode: Measured)
	/// The range of component `s` is `[0, 100000]`.
	fn revoke_key(_s: u32, ) -> Weight {
		Weight::from_parts(10_046_402, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: Keystore IssuedEncryptionKeys (r:0 w:1)
	/// Proof: Keystore IssuedEncryptionKeys (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 100000]`.
	fn issue_encryption_key(_s: u32, ) -> Weight {
		Weight::from_parts(8_890_164, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: Keystore IssuedKeys (r:0 w:1)
	/// Proof Skipped: Keystore IssuedKeys (max_values: None, max_size: None, mode: Measured)
	/// The range of component `s` is `[0, 100000]`.
	fn announce_key(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_448_118, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Keystore IssuedKeys (r:0 w:1)
	/// Proof Skipped: Keystore IssuedKeys (max_values: None, max_size: None, mode: Measured)
	/// The range of component `s` is `[0, 100000]`.
	fn revoke_key(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 9_000_000 picoseconds.
		Weight::from_parts(10_046_402, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: Keystore IssuedEncryptionKeys (r:0 w:1)
	/// Proof: Keystore IssuedEncryptionKeys (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
	/// The range of component `s` is `[0, 100000]`.
	fn issue_encryption_key(_s: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 8_000_000 picoseconds.
		Weight::from_parts(8_890_164, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}