
//! Autogenerated weights for `pallet_fennel_identity`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-19, STEPS: `100`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("fennel-local"), DB CACHE: 1024

// Executed Command:
// ./target/release/fennel-node
// benchmark
// pallet
// --chain=fennel-local
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_fennel_identity
// --extrinsic=*
// --steps=100
// --repeat=10
// --template=./scripts/templates/parachain-weight-template.hbs
// --output=./runtime/fennel/src/weights

#![allow(unused_parens, unused_imports)]
#![allow(clippy::unnecessary_cast, clippy::missing_docs_in_private_items)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_fennel_identity` using the recommended hardware.
pub struct WeightInfo<T>(pub PhantomData<T>);
impl<T: frame_system::Config> pallet_fennel_identity::WeightInfo for WeightInfo<T> {
	// Storage: Identity IdentityNumber (r:1 w:1)
	// Proof: Identity IdentityNumber (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	// Storage: Identity IdentityList (r:1 w:1)
	// Proof Skipped: Identity IdentityList (max_values: None, max_size: None, mode: Measured)
	fn create_identity(s: u32, ) -> Weight {
		Weight::from_ref_time(14_374_983 as u64)
			// Standard Error: 1
			.saturating_add(Weight::from_ref_time(1 as u64).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Identity RevokedIdentityNumber (r:1 w:1)
	// Proof: Identity RevokedIdentityNumber (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	// Storage: Identity IdentityList (r:1 w:1)
	// Proof Skipped: Identity IdentityList (max_values: None, max_size: None, mode: Measured)
	fn revoke_identity(_s: u32, ) -> Weight {
		Weight::from_ref_time(16_003_562 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Identity IdentityList (r:1 w:0)
	// Proof Skipped: Identity IdentityList (max_values: None, max_size: None, mode: Measured)
	// Storage: Identity IdentityTraitList (r:1 w:1)
	// Proof Skipped: Identity IdentityTraitList (max_values: None, max_size: None, mode: Measured)
	fn add_or_update_identity_trait(s: u32, ) -> Weight {
		Weight::from_ref_time(15_337_460 as u64)
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(3 as u64).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: Identity IdentityList (r:1 w:0)
	// Proof Skipped: Identity IdentityList (max_values: None, max_size: None, mode: Measured)
	// Storage: Identity IdentityTraitList (r:0 w:1)
	// Proof Skipped: Identity IdentityTraitList (max_values: None, max_size: None, mode: Measured)
	fn remove_identity_trait(s: u32, ) -> Weight {
		Weight::from_ref_time(14_263_894 as u64)
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(1 as u64).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(1 as u64))
			.saturating_add(T::DbWeight::get().writes(1 as u64))
	}
	// Storage: Identity IdentityList (r:1 w:0)
	// Proof Skipped: Identity IdentityList (max_values: None, max_size: None, mode: Measured)
	// Storage: Identity SignalCount (r:1 w:1)
	// Proof: Identity SignalCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	// Storage: Identity SignatureSignal (r:0 w:1)
	// Proof Skipped: Identity SignatureSignal (max_values: None, max_size: None, mode: Measured)
	fn sign_for_identity(s: u32, ) -> Weight {
		Weight::from_ref_time(17_972_873 as u64)
			// Standard Error: 0
			.saturating_add(Weight::from_ref_time(4 as u64).saturating_mul(s as u64))
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
}
