
//! Autogenerated weights for `pallet_trust`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-19, STEPS: `100`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("fennel-local"), DB CACHE: 1024

// Executed Command:
// ./target/release/fennel-node
// benchmark
// pallet
// --chain=fennel-local
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_trust
// --extrinsic=*
// --steps=100
// --repeat=10
// --template=./scripts/templates/parachain-weight-template.hbs
// --output=./runtime/fennel/src/weights

#![allow(unused_parens, unused_imports)]
#![allow(clippy::unnecessary_cast, clippy::missing_docs_in_private_items)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_trust` using the recommended hardware.
pub struct WeightInfo<T>(pub PhantomData<T>);
impl<T: frame_system::Config> pallet_trust::WeightInfo for WeightInfo<T> {
	// Storage: Trust TrustIssuance (r:1 w:1)
	// Proof: Trust TrustIssuance (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	// Storage: Trust CurrentIssued (r:1 w:1)
	// Proof: Trust CurrentIssued (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn issue_trust() -> Weight {
		Weight::from_ref_time(14_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Trust TrustRevocation (r:1 w:1)
	// Proof: Trust TrustRevocation (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	// Storage: Trust CurrentRevoked (r:1 w:1)
	// Proof: Trust CurrentRevoked (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn revoke_trust() -> Weight {
		Weight::from_ref_time(14_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Trust TrustIssuance (r:1 w:1)
	// Proof: Trust TrustIssuance (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	// Storage: Trust CurrentIssued (r:1 w:1)
	// Proof: Trust CurrentIssued (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn remove_trust() -> Weight {
		Weight::from_ref_time(19_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Trust TrustRevocation (r:1 w:1)
	// Proof: Trust TrustRevocation (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	// Storage: Trust CurrentRevoked (r:1 w:1)
	// Proof: Trust CurrentRevoked (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn remove_revoked_trust() -> Weight {
		Weight::from_ref_time(18_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Trust TrustRequestList (r:1 w:1)
	// Proof: Trust TrustRequestList (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	// Storage: Trust CurrentRequests (r:1 w:1)
	// Proof: Trust CurrentRequests (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn request_trust() -> Weight {
		Weight::from_ref_time(14_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
	// Storage: Trust TrustRequestList (r:1 w:1)
	// Proof: Trust TrustRequestList (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	// Storage: Trust CurrentRequests (r:1 w:1)
	// Proof: Trust CurrentRequests (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn cancel_trust_request() -> Weight {
		Weight::from_ref_time(17_000_000 as u64)
			.saturating_add(T::DbWeight::get().reads(2 as u64))
			.saturating_add(T::DbWeight::get().writes(2 as u64))
	}
}
