//! Autogenerated weights for `pallet_keystore`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-02-18, STEPS: `20`, REPEAT: 100, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/node-fennel-protocol
// benchmark
// --chain
// dev
// --execution
// wasm
// --wasm-execution
// compiled
// --pallet
// pallet_keystore
// --extrinsic
// *
// --steps
// 20
// --repeat
// 100
// --raw
// --output
// ./

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}, dispatch::WeighData};
use core::marker::PhantomData;

pub trait WeightInfo {
    fn announce_key() -> Weight;
    fn revoke_key() -> Weight;
}

/// Weight functions for `pallet_keystore`.
pub struct SubstrateWeights<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeights<T> {
	// Storage: KeystoreModule IssuedKeys (r:0 w:1)
	fn announce_key() -> Weight {
		(19_171_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: KeystoreModule IssuedKeys (r:0 w:1)
	fn revoke_key() -> Weight {
		(22_594_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}

impl WeightInfo for () {
	// Storage: KeystoreModule IssuedKeys (r:0 w:1)
	fn announce_key() -> Weight {
		(19_171_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: KeystoreModule IssuedKeys (r:0 w:1)
	fn revoke_key() -> Weight {
		(22_594_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}
